apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elasticsearch-default-es-http:9200
        tls:
          ca: /es-certs/ca.crt
        username: elastic
    secretName: es-cred
  volumeMounts:
    - name: es-certs
      mountPath: /es-certs
      readOnly: true
  volumes:
    - name: es-certs
      secret:
        secretName: elasticsearch-default-es-http-certs-public