apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend
  labels:
    app: spring-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend
  template:
    metadata:
      labels:
        app: spring-backend
    spec:
      containers:
      - name: spring-backend
        image: spring-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 6565
---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 6565
  selector:
    app: spring-backend