apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend-2
  labels:
    app: spring-backend-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-backend-2
  template:
    metadata:
      labels:
        app: spring-backend-2
    spec:
      containers:
      - name: spring-backend-2
        image: spring-backend-2
        imagePullPolicy: Never
        ports:
        - containerPort: 6566
---
apiVersion: v1
kind: Service
metadata:
  name: spring-backend-2
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 6566
  selector:
    app: spring-backend-2